const activityReferences={
bounties:['voyage-board','Bounty record','Atul · 17 Valnuary, 932 AF','Recorded rewards; current availability unverified','Report successful missions to the Admiral, Ministry of Defense, or a Regent. The supplied board requires a Petty Officer or Battle Officer captaining an HN vessel; lower-ranked sailors can crew toward promotion. These titles differ from PROGRESSION’s five roles. The scroll says one claim at a time but permits multiple permanent enemy-sinking claims together, capped at 200k per year. Ask the Admiral to resolve eligibility and current availability.'],
deepseadiving:['hunting-chart','Deep-sea diving','Alizais · 19 Valnuary, 947 AF; guide credited to Czanthria','Account for every diver before raising the bell','Raising the bell while anyone remains on the floor kills them, according to the scroll. Use SHIP TAKE SOUNDING with a leadline, keep a lookout topside, and bring spare shovels unless you have the artefact shovel. A leadline requires 10 leather and 40 rope from a Shipfitter. SHIP LEAVE BELL permits returning topside while the bell remains down; re-entry waits until it is topside. Pale-bone chests can summon a seamonster; the source’s gold amounts are observations rather than guaranteed rewards. The 13×13 grid assigns each letter a 10×10-metron ocean square. Full floor maps and creature/reagent records are preserved below.'],
deepseatreasure:['hunting-chart','Diving treasure','Rhydian · 8 Glacian, 883 AF','Dig · creatures · chests','The source orders its treasure list from common junk to rarer items. Dig with a shovel, recover items from creatures, or open chests. Coral-chest instructions differ slightly between the diving and treasure scrolls: the former says PUSH CHEST, while the latter lists repeated turn/push/pull/twist. Steel chests may require a recovered key or TURN CHEST HANDLE RIGHT followed by a wait. Spare ordinary shovels are advised because they can break.'],
kraken:['hunting-chart','Kraken reference','Icraa · 21 Mayan, 923 AF','Tentacle targeting · range · survival','Begin by firing at TENTACLE rather than SEAMONSTER. The recorded advice circles near the edge, commonly clockwise, at maximum ballista range. If taking hits, leave the kraken’s reach first; at low hull, move to the edge and anchor for repairs while watching its approach. Starshot and spidershot may help within reach. The source says surviving ships receive a tentacle. VOYAGELIST says to obtain the Indebted Voyage before summoning. The supplied KRAKEN scroll has no complete summoning procedure.'],
seamonsterareas:['hunting-chart','Hunting areas','Rhydian · 8 Glacian, 883 AF','Recorded areas; no invented coordinates','Seamonsters can surface anywhere. The scroll identifies concentrations and approach/avoidance directions by region. Northern sites do not state monster levels. Area levels conflict in places with the separate SEAMONSTERS nest descriptions, including west of Phereklos; preserve both and verify before planning a hunt.'],
seamonsters:['hunting-chart','Seamonster levels and ammunition','Micharoj · 17 Ero, 914 AF','Complete supplied source · level table available','Use FIRE <weapon> AT SEAMONSTER rather than a ship target lock. Darts from a ballista and discs from a thrower count as damaging shots. Onager spidershot reduces next-attack damage, starshot temporarily slows attack speed, and chainshot slows movement; flares from any weapon temporarily stop movement. The complete supplied description catalogue includes all 19 named monsters, with the MORE continuation joined beneath its original attribution.'],
shiptrades:['merchants-ledger','Accepting ship trades','Alizais · 13 Mayan, 969 AF','Harbour offer → accept → route → deliver','HARBOUR INFO at Tasur’ke or Thraasi shows offers; SHIP TRADE aboard lists required commands. Offers change monthly at Serenade; accept before the offer’s month ends, while the accepted trade has no completion time limit in this scroll. Personal and ship restrictions may apply separately or together. City ships are first-come, first-served: check their logs, finish promptly, and restore cargo costs and docking fees to the strongbox.'],
tradecargo:['merchants-ledger','Cargo exchange directory','Zorina · 7 Aeguary, 935 AF','Input cargo → recorded exchange → output cargo','Each “Price” is the input and “Cargo for trade” is the output. Six recorded starter goods cost 1,000 gp per unit: salt at Zaphar, wool at Tasur’ke, sandstone and cotton at Shastaan, grain and ore at Thraasi. Port fees belong to this source and differ from some earlier harbour entries. The searchable exchange directory below preserves cargo spellings, including kahwe and furs.'],
tradedealchart:['merchants-ledger','Trade-deal chart','Minkai · 7 Phaestian, 930 AF; research/design Favonius Stormcrow-Xanatov; chart Lisbethe Etienne Le’Murzen-Sparrow','Recorded trade graph','The diagram links starter goods through harbour exchanges to later cargo. Its ASCII layout is retained in the source panel rather than redrawn with uncertain edges. Use TRADECARGO’s explicit exchange rows and TRADEMATH’s input/output formula when planning quantities; do not infer missing current prices or deals.'],
trademath:['merchants-ledger','Trade calculations','Minkai · 1 Lupar, 950 AF; guide credited to Rhydian Malicieux','Output = input × output-ratio ÷ input-ratio','The recorded example starts with 12 sandstone, exchanges 4:3 at Tasur’ke for 9 granite, then 3:2 at Karbaz for 6 marble. Delivery requires 5 marble, leaving one extra. The calculator below uses this formula without inventing game rounding rules. Fractional outputs are flagged; fees, cargo capacity, rewards, and profit are outside the quantity calculation.'],
traderewards:['merchants-ledger','Recorded trade rewards','Rhydian · 8 Glacian, 883 AF','Rewards listed by the source; current offers not implied','The source lists gold awards of 65k, 75k, 100k, or 200k and bound credits of 5, 10, or 25, plus crew morale/experience, ammunition, and item rewards. Examples include rum, a captain’s hat, Notic amulet, Safe Passage skull, furniture crate, dice, flare, birds, mounts, and a ship kitten. Details, durations, and the source’s assessments are in the original. Check HARBOUR INFO for the offered trade.'],
traderouteguide:['merchants-ledger','Route planning','Iolanthe · 4 Miraman, 727 AF; guide Captain Zbaco Silvertongue','Starting harbour → exchanges → ending harbour','Write down each stop, inbound/outbound cargo and quantities, and its exchange ratio. Carry the output of one row into the next input. This guide shares the 12 sandstone → 9 granite → 6 marble example with TRADEMATH but has different authorship and credits; both originals remain separate.'],
voyagelist:['voyage-board','Voyage directory','Icraa · 4 Ero, 924 AF','11 recorded voyages · conditions and hints','The source lists where to obtain each voyage, approximate length, and limited hints. Sight requires the crew to have completed most other voyages and appears at one changing location among Claw Cove, New Hope, Valho Coast, or Sea Lion Cove. Fog-wreathed must be requested immediately after Sight from the same dockworker. Do not infer current availability or exact rewards from the list.'],
voyages:['voyage-board','Requesting a voyage','Rhydian · 8 Glacian, 883 AF','Docked ship · assumed command · crew permissions','At the appropriate harbour, a captain requests SAY REQUESTING A VOYAGE FOR SHIP <#>. The ship must be docked there, the requester must have assumed command, and participating crew must be aboard with CREW permissions. QUEST LOG OCEANS shows signed-up voyages. A captain cannot request a voyage while already holding one, though the scroll notes other ways to obtain additional voyages. Some depend on time, harbour, or prerequisites. Gold and renown go to participants; talisman pieces usually go to the captain, with exceptions.']
};
const activityGroups={'hunting-chart':['seamonsters','seamonsterareas','kraken','deepseadiving','deepseatreasure'],'merchants-ledger':['shiptrades','tradecargo','tradedealchart','trademath','traderewards','traderouteguide'],'voyage-board':['voyages','voyagelist','bounties']};
function activitySafe(v){return v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');}
for(const [section,topics]of Object.entries(activityGroups)){const body=document.querySelector('#'+section+' .reference-body');body.innerHTML='<div class="at-glance"><p class="label">01 / CHOOSE YOUR REFERENCE</p><div class="topic-flow">'+topics.map(t=>'<a href="#activity-'+t+'">'+activityReferences[t][1]+'</a>').join('')+'</div></div>'+topics.map(topic=>{const [section,title,credit,quick,prose]=activityReferences[topic];return '<details class="reference activity-detail" id="activity-'+topic+'"><summary><div><span class="label">'+quick+'</span><h2>'+title+'</h2></div><span class="toggle" aria-hidden="true">+</span></summary><div class="reference-body"><div class="at-glance"><p class="label">01 / AT A GLANCE</p><h3>'+quick+'</h3><div id="activity-visual-'+topic+'"></div></div><div class="editorial"><p class="label">02 / WORKING REFERENCE · EDITORIAL</p><p>'+activitySafe(prose)+'</p></div><div id="activity-extra-'+topic+'"></div><details class="source-box"><summary>03 / ORIGINAL CLHELP '+topic.toUpperCase()+' · '+credit+'</summary><p><a href="records/'+topic+'.txt">Read the exact returned text'+''+'</a></p><pre class="exact-scroll activity-source" data-activity-source="'+topic+'"></pre></details></div></details>';}).join('');document.querySelector('#'+section+' summary .small').textContent='All section topics received'+'';}
const monsterLevels=[['1','20','5,000','Flying Sheilei; Foam-Wreathed Sea Serpent; Mudback Septacean; Red-Faced Septacean'],['2','25','7,500','Mass of Sargassum; Gargantuan Angler Fish; Gargantuan Megalodon; Raging Shraymor'],['3','30','15,000','Furious Sea Dragon; Pirate Ship; Red-Sailed Kashari Raider; Trio of Raging Sea Serpents'],['4','40','50,000','Monstrous Ketea; Monstrous Picaroon; Sea Hag; Unmarked Warship'],['5','60','100,000','Hulking Oceanic Cyclops; Legendary Leviathan; Towering Oceanic Hydra']];
document.querySelector('#activity-visual-seamonsters').innerHTML=basicsTable('Recorded levels',['Level','Dart/disc shots','Trophy gold','Names'],monsterLevels);
const voyagesList=[['Tourist','Thraasi, Otryn present','Long; six places','Keep the tourist following.'],['Treasure','Corked glass bottle in harbour; open aboard','Short; one destination','Read the map and clues.'],['Captain’s','Harbourmaster, man-made harbour','Medium; several days','Share finds with the pangolin.'],['Indebted','Harbourmaster, man-made harbour','Variable; kraken hunt','Obtain before kraken summoning.'],['Surgeon’s','Averroes, New Hope','Long; one island per ocean','Obtain offerings before visiting the four spirits.'],['Cursed','Harbourmaster, man-made harbour','Long; several islands and quests','Fetch the items needed for Yudhishthira’s help.'],['Smuggler','Island dockworkers','Short','Deliver goods to another island.'],['Priestess','Riparium, new moon','Short','Dig up and place the skull as needed.'],['Grievous','Any voyage-offering harbour','Longest','Source advises a dragon crew; very dangerous.'],['Sight','Claw Cove / New Hope / Valho Coast / Sea Lion Cove; changes','Short; difficult fight','Most other voyages required for you and crew; bring dragon crew.'],['Fog-wreathed','Same dockworker immediately after Sight','Short','Travel into the mist; source supplies no further steps.']];
document.querySelector('#activity-visual-voyagelist').innerHTML=basicsTable('Voyages in the supplied record',['Voyage','Obtained at','Length','Hint / condition'],voyagesList);
document.querySelector('#activity-visual-bounties').innerHTML=basicsTable('932 AF bounty board · historical record, not live availability',['Bounty','Recorded gold','Source status'],[['City enemy','30,000','OPEN, REPEATABLE; yearly 200k cap'],['Landon','50,000','OPEN in source'],['Last Word','50,000','OPEN in source'],['Artanis','50,000','OPEN in source'],['Ashtani ships (ANS, privately owned, or captained by Ashtani)','50,000','OPEN in source']]);
document.querySelector('#activity-visual-voyages').innerHTML='<code>SAY REQUESTING A VOYAGE FOR SHIP &lt;#&gt;</code><p>Check participation with <code>QUEST LOG OCEANS</code>.</p>';
document.querySelector('#activity-visual-deepseadiving').innerHTML='<p><strong>Never raise the bell until every diver is accounted for.</strong></p><pre class="dive-grid">COWRMPITNBAJF\nMPITNBAJFCOWR\nNBAJFCOWRMPIT\nFCOWRMPITNBAJ\nRMPITNBAJFCOW\nTNBAJFCOWRMPI\nJFCOWRMPITNBA\nWRMPITNBAJFCO\nITNBAJFCOWRMP\nAJFCOWRMPITNB\nOWRMPITNBAJFC\nPITNBAJFCOWRM\nBAJFCOWRMPITN</pre><p>Each letter: a 10×10-metron square. The individual floor maps remain in the original.</p>';
const calc=document.createElement('section');calc.id='trade-calculator';calc.className='at-glance';calc.innerHTML='<p class="label">TRADE QUANTITY CALCULATOR · TRADEMATH FORMULA</p><h3>Two exchanges, one cargo plan</h3><p>Default example: sandstone → granite → marble. Edit quantities and input:output ratios for your planned exchanges.</p><div class="calc-grid"><label>Starting cargo units<input id="trade-start" type="number" min="0" step="any" value="12"></label><label>First input:output ratio<input id="trade-ratio-one" value="4:3"></label><label>Second input:output ratio<input id="trade-ratio-two" value="3:2"></label></div><p id="trade-result" role="status"></p><p class="small">Exact arithmetic only. Fractional units are flagged; in-game rounding is not supplied. No fees, capacity, profit, or reward calculation.</p>';
document.querySelector('#activity-extra-trademath').append(calc);
function tradeQuantity(start,one,two){const ratio=s=>{const m=/^\s*(\d+(?:\.\d+)?)\s*:\s*(\d+(?:\.\d+)?)\s*$/.exec(s);if(!m||Number(m[1])<=0||Number(m[2])<=0)throw Error('Use positive input:output ratios, such as 4:3.');return Number(m[2])/Number(m[1]);};if(!Number.isFinite(start)||start<0)throw Error('Enter a non-negative starting quantity.');const first=start*ratio(one);const second=first*ratio(two);if(!Number.isFinite(first)||!Number.isFinite(second))throw Error('These quantities exceed the calculator range.');return [first,second];}
function calculateTrade(){const result=document.querySelector('#trade-result');try{const raw=document.querySelector('#trade-start').value;if(!raw.trim())throw Error('Enter the starting quantity.');const [first,last]=tradeQuantity(Number(raw),document.querySelector('#trade-ratio-one').value,document.querySelector('#trade-ratio-two').value);const fractional=[first,last].some(n=>Math.abs(n-Math.round(n))>1e-8);result.textContent='After exchange 1: '+Number(first.toFixed(6))+' units · After exchange 2: '+Number(last.toFixed(6))+' units'+(fractional?' · Fractional output: verify valid whole-cargo quantities before trading.':'');}catch(e){result.textContent=e.message;}}
calc.querySelectorAll('input').forEach(el=>el.addEventListener('input',calculateTrade));calculateTrade();
for(const topic of Object.keys(activityReferences)){const record=document.querySelector('#scroll-'+topic);record.querySelector('summary .small').textContent=activityReferences[topic][0].replaceAll('-',' ')+' · '+'Original supplied';record.querySelector('p').innerHTML='<a href="#activity-'+topic+'">Read the working reference</a> · <a href="records/'+topic+'.txt">Read the supplied source</a>';}
async function loadActivity(topic){try{const response=await fetch('records/'+topic+'.txt');if(!response.ok)throw Error('Unavailable');const text=await response.text();document.querySelector('[data-activity-source="'+topic+'"]').textContent=text;if(topic==='tradecargo'){const rows=[];let port='';for(const line of text.split('\n')){if(/^[\w '\-]+\s*:\s*\(/.test(line))port=line.trim();const m=/Cargo for (trade|sale): (.+)\. Price: (.+)\./.exec(line);if(m)rows.push([port,m[3],m[2],m[1]]);}document.querySelector('#activity-visual-tradecargo').innerHTML=basicsTable('Recorded cargo exchanges',['Harbour / fee','Input / price','Output','Exchange'],rows);}if(topic==='deepseatreasure'){const lines=text.split('\n');const start=lines.findIndex(l=>l.trim()==='a silver seashell hand mirror');const end=lines.findIndex(l=>l.startsWith('You can get these'));document.querySelector('#activity-visual-deepseatreasure').innerHTML='<ol class="treasure-list">'+lines.slice(start,end).filter(l=>l.trim()).map(l=>'<li>'+activitySafe(l.trim())+'</li>').join('')+'</ol>';}if(topic==='seamonsterareas'){const body=text.split(/Composed by:[^\n]*\n/)[1];document.querySelector('#activity-visual-seamonsterareas').innerHTML='<div class="area-list">'+body.trim().split(/\n\s*\n/).slice(1).map(b=>'<p>'+activitySafe(b.replace(/\s*\n\s*/g,' ').trim())+'</p>').join('')+'</div>';}}catch{document.querySelector('[data-activity-source="'+topic+'"]').textContent='Use the original source link above.';}}
Object.keys(activityReferences).forEach(loadActivity);
