const commandGroups=[
['Ship abilities',['INVOKE SEA SPIRIT','SEASPELL INVESTED','AURA STATUS','SHIPWARNING ON'],'Invoke the sea spirit at the figurehead to meld for seaspells. Inspect invested seaspells and active auras; enable nearby ship warnings.'],
['Ammunition',['SHIP AMMO','SHIP AMMO STATUS','SHIP AMMO ADD <crate#>','SHIP AMMO REMOVE <#> <ammunitiontype>'],'Inspect ammunition, add a crate, or remove a specified quantity and type.'],
['Load and unload',['LOAD <weapon> WITH <ammo>','LOAD <weapon> WITH <ammo> DIPPED','UNLOAD <ammo> from <weapon>'],'The supplied scroll lists both ordinary and dipped loading syntax. It does not explain dipping requirements.'],
['Fire and target',['FIRE <weapon> AT <seamonster>','FIRE <weapon> AT <shiptarget>','SHIP TARGET LOCK <ship>','SHIP TARGET LOCK CLEAR','FIRE <weapon>'],'FIRE <weapon> alone applies when the ship has locked onto a target. Read Naval Policy before engaging a vessel.'],
['Clear entanglements',['CHOP TETHER','CLIMB RIGGING','CLEAR RIGGING','CLEAR FIGUREHEAD','CLEAR <weapon>'],'CHOP TETHER addresses grappled hookshots. The clearing abilities are channeled: remain in place until execution completes.'],
['Control fires',['FILL BUCKET WITH WATER','DOUSE ROOM|GROUND','DOUSE <person>|<item>','DOUSE FIRE'],'Have a bucket and rope in hand aboard ship. Filling requires rope and an empty bucket. DOUSE FIRE from the crow’s nest douses the sails.'],
['Spyglass',['SPYGLASS','SPYGLASS LOOK','SPYGLASS INFO <seamonster>'],'Look for ships and seamonsters within a small radius. INFO gives information about a specified seamonster.']
];
function escapeCommand(value){return value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');}
const commandSection=document.createElement('section');commandSection.id='captain-commands';commandSection.innerHTML='<div class="at-glance"><p class="label">01 / BASIC CAPTAIN COMMANDS · SOURCE-BASED REFERENCE</p><div class="command-grid">'+commandGroups.map(([title,commands])=>'<div><h3>'+title+'</h3>'+commands.map(c=>'<code>'+escapeCommand(c)+'</code>').join('')+'</div>').join('')+'</div></div><div class="editorial"><p class="label">02 / THE WORKING REFERENCE · EDITORIAL SUMMARY</p>'+commandGroups.map(([title,commands,note])=>'<p><strong>'+title+':</strong> '+escapeCommand(note)+'</p>').join('')+'<p><a href="#naval-policy">Read the foreign-ships policy →</a></p><p class="small">The pasted source does not include a helpfile command or topic heading. It is provisionally indexed under basiccommands from the site plan; its exact topic name awaits confirmation.</p></div><details class="source-box"><summary>03 / ORIGINAL COMMAND LIST · RHYDIAN · 8 GLACIAN, 883 AF</summary><p>The scroll credits Ilsefi for composing the list. <a href="records/captain-basic-commands.txt">Read the exact supplied text</a>.</p><pre class="exact-scroll" id="commands-original"></pre></details>';
document.querySelector('#quarterdeck .reference-body').prepend(commandSection);
document.querySelector('#quarterdeck summary .small').textContent='Captain command list supplied · introductory topics await source';
for(const id of ['battle-stations','ships-book'])document.querySelector('#'+id+' .editorial').insertAdjacentHTML('beforeend','<p><a href="#captain-commands">Open the captain’s command reference →</a></p>');
const commandRecord=document.querySelector('#scroll-basiccommands');commandRecord.querySelector('summary .small').textContent='The Quarterdeck · Command list supplied; topic provisional';commandRecord.querySelector('p').innerHTML='<a href="#captain-commands">Read the captain’s command reference</a> · <a href="records/captain-basic-commands.txt">Exact supplied text</a>. The original paste did not include the helpfile topic heading.';
fetch('records/captain-basic-commands.txt').then(r=>{if(!r.ok)throw new Error('Unavailable');return r.text();}).then(text=>{document.querySelector('#commands-original').textContent=text;}).catch(()=>{document.querySelector('#commands-original').textContent='Use the exact source link above.';});
