const navyGuides={
buyingaship:['ships-book','Buying a ship','Kuriel · 25 Phaestian, 849 AF','Compare commodity cost with the commission discount','The source’s recommendation favours shipcloth and shiplines under its historical market conditions. Its strider example instead names 300 shipiron with 300 shiplines, conflicting with the recommendation and the listed commodity maxima; do not treat that example as a confirmed shopping list. Check HELP SHIPTYPES and commodity prices before commissioning. Commodities must be held outside the rift to count toward a discount. Recorded base prices are 2.5m gold for a cutter, 5m for a strider, and 10m for a galley; these are not verified live quotes.'],
crew:['ships-book','Denizen crew','Rhydian · 6 Glacian, 883 AF','Rowing · repairs · defence','Crewmates support rowing and endurance, shipmates support repairs, and swashbucklers defend aboard ship. Swashbucklers cannot be assigned stations and can be trapped behind closed doors. The source recommends generous wages and maximum Helm aura while training; fed and paid crew retain morale. Crewmates and shipmates learn through their duties; swashbucklers gain experience from monster kills, crew-experience trades, and plundering encounters. Recorded base wages are 4 bits for crewmates, 6 bits for shipmates, and 2 gold 4 bits for swashbucklers; reduce wages gradually and restore morale as described in the original.'],
mapold:['chartroom','Historical sea map','Mosr · 3 Glacian, 682 AF','Original ASCII chart and A–R key','The supplied map is a historical schematic, not a scaled navigation chart or current coordinate source. Keep its fixed-width layout when viewing it. Place-name spellings belong to this record; no new sailing routes or bearings are inferred.'],
needammo:['ships-book','Navy ammunition','Nezaya · 11 Ero, 946 AF','Recorded price: 100 gold per unit','The scroll permits citizen purchases at its recorded price. Leave at least 1,000 of the relevant ammunition type aboard Navy ships; if already below that level, alert the Admiral and remove none of that type. Donate surplus by storing it aboard and messaging the Admiral. Verify current sale terms with the Admiral or a Maritime aide. CITYSHIPS separately specifies cutter flare requirements and larger-ship ammunition targets; preserve these contexts rather than replacing one with the other.'],
newship:['ships-book','Outfit a new vessel','Kuriel · 16 Glacian, 829 AF','Crew → stores → strongbox → weapons → figurehead → name and flag','Inspect available crew with HARBOUR CREW FORHIRE at Thraasi, Tasur’ke, or Shastaan; hire through HARBOUR commands and check SHIP CREW. Purchase tokens equal to three times total crew, and the guide recommends 10 common stores initially. Cook stores to support morale. Deposit and check the strongbox in the cabin; the guide recommends no more than 20–30k gold, while naval class requirements remain in CITYSHIPS. Check weapon status and consider nondecaying weapons. Review SEASPELLS for the figurehead. The guide’s Petty Officer reference differs from the newer PROGRESSION role list.'],
seaspells:['ships-book','Figureheads and seaspells','Minkai · 19 Mayan, 832 AF','Consecrate → mount → meld → invest in harbour','The source places seaspells at 423 lessons, except Hunger. Take the figurehead to the Altar of Sea Spirits roughly southwest of Zaphar’s port, place it down, and PRAY TO SEA SPIRITS; mount it at the bow with SHIP MOUNT <figurehead>. INVOKE SEA SPIRIT melds at the bow. The scroll prints RELSEASE SEA SPIRIT, apparently a command typo; no corrected runnable command is inferred here. TOUCH FIGUREHEAD while melded checks power. Fully drained ordinary figureheads are destroyed; resetting ones detach and require reconsecration. Invest while in harbour: four of eight investable spells, with Shipcloak/Wavecall and Shield/Rainstorm mutually exclusive. Hunger needs no investment and this scroll requires melding for Hunger and Wavecall.'],
shipequipment:['ships-book','Equipment and materials','Rhydian · 9 Glacian, 883 AF','Purpose · placement · commodity cost','Use TRADEWHO SHIPFITTING to find a crafter and HELP SHIP EQUIPMENT for details. Equipment descriptions and component lists are shown below. The multipurpose crane entry says 25 shipiron but gives an expansion of 750 iron and 150 steel; the stated conversion would give 1,250 iron and 250 steel. Both source figures remain intact pending confirmation. Cargo floats add 25 capacity for 30 months; cargo buoys offer one-use cargo recovery protection subject to the listed permissions and expiry rules.'],
shipfitting:['ships-book','Sails, hull finishes, and trim','Rhydian · 23 Ero, 886 AF','Choose class → base materials → pigment or trim samples','A Shipfitter can dye sails or paint, stain, and trim hulls. Ships modified by an artefact pail must first be restored before further fitting. Choose the base materials for your ship class and add the listed pigment mix or ten samples of the trim material. Full colour recipes and material names remain in the original scroll. Modified sails appear in shipwarning; hull and sail details appear through the listed SHIP LOOK commands.'],
statues:['chartroom','Sea-marker statues','Rhydian · 9 Glacian, 883 AF','18 recorded relative locations','The source lists 18 known statue sites by region, using coasts, chops, islands, and monster nests as landmarks. These are relative descriptions, not coordinates. The original descriptions of the six statue forms are preserved below without adding interpretation or lore.']
};
for(const [topic,[section,title,credit,quick,summary]] of Object.entries(navyGuides)){const entry=document.createElement('details');entry.className='reference guide-detail';entry.id='guide-'+topic;entry.innerHTML='<summary><div><span class="label">'+quick+'</span><h2>'+title+'</h2></div><span class="toggle" aria-hidden="true">+</span></summary><div class="reference-body"><div class="at-glance"><p class="label">01 / AT A GLANCE</p><h3>'+quick+'</h3><div id="guide-visual-'+topic+'"></div></div><div class="editorial"><p class="label">02 / WORKING REFERENCE · EDITORIAL</p><p>'+activitySafe(summary)+'</p></div><div id="guide-details-'+topic+'"></div><details class="source-box"><summary>03 / ORIGINAL CLHELP '+topic.toUpperCase()+' · '+credit+'</summary><p><a href="records/'+topic+'.txt">Read the exact source scroll</a></p><pre class="exact-scroll activity-source" data-guide-source="'+topic+'"></pre></details></div>';document.querySelector('#'+section+' .reference-body').append(entry);const record=document.querySelector('#scroll-'+topic);record.querySelector('summary .small').textContent='Original source supplied';record.querySelector('p').innerHTML='<a href="#guide-'+topic+'">Read the guide</a> · <a href="records/'+topic+'.txt">Exact source</a>';}
document.querySelector('#guide-visual-crew').innerHTML=basicsTable('Recommended denizen crew',['Class','Crewmates','Shipmates','Swashbucklers','Recorded hiring total'],[['Windcutter',24,15,3,'72,000g'],['Seastrider',60,40,5,'225,000g'],['War Galley',70,50,6,'275,000g']])+basicsTable('Hiring and useful limits',['Type','Hire cost','Cutter maximum useful','Strider maximum useful','Galley maximum useful'],[['Crewmates','500g',24,60,70],['Shipmates','3,000g',15,40,50],['Swashbucklers','5,000g',3,8,11]]);
document.querySelector('#guide-visual-seaspells').innerHTML=basicsTable('Recorded seaspell power',['Spell','Power cost','Constraint / effect'],[['Hunger',300,'Level 2.5+ monsters; melded; no investment'],['Shipcloak',250,'Exclusive with Wavecall; flares reveal'],['Wavecall','Varies','1–8 metrons; melded; hull/endurance costs; not grappled'],['Shield',200,'Exclusive with Rainstorm; Wavescythe breaks it'],['Rainstorm',50,'Douses decks and sails'],['Barrier',300,'Continuing replacements cost more power; dissolve to stop'],['Windboost',150,'Temporary speed boost'],['Whirlpool',200,'Slows passage around ship'],['Wavescythe',200,'Breaks another ship’s shield in range']]);
document.querySelector('#guide-visual-buyingaship').innerHTML=basicsTable('Recorded ship-commodity conversions',['Commodity','Raw materials','Commission value in source'],[['Shipwood','50 wood + 10 iron','3,000g'],['Shipiron','50 iron + 10 steel','2,250g'],['Shipcloth','50 cloth','1,750g'],['Shiplines','50 rope + 10 iron','1,750g'],['Pitch','50 wood + 10 animal fat','3,000g']]);
document.querySelector('#guide-visual-newship').innerHTML='<div class="topic-flow"><span>Crew</span><span>Token/food stores</span><span>Strongbox</span><span>Weapons</span><span>Figurehead</span><span>Name / alias / flag</span></div>';
document.querySelector('#guide-visual-needammo').innerHTML='<div class="command-grid"><code>DEPOSIT ## GOLD HN &lt;reason&gt;</code><code>SHIP AMMO STATUS</code><code>SHIP AMMO REMOVE ## &lt;ammo type&gt;</code><code>SHIP AMMO STORE &lt;ammo type&gt;</code></div><p>STORE is printed without a number.</p>';
document.querySelector('#guide-visual-shipfitting').innerHTML=basicsTable('Base fitting materials; pigments/samples additional',['Class','Sail dye','Hull paint/stain','Hull trim'],[['Windcutter','15 shipcloth','5 shipwood','5 shipwood + 5 shipiron'],['Seastrider','30 shipcloth','15 shipwood','10 shipwood + 10 shipiron'],['War Galley','60 shipcloth','30 shipwood','20 shipwood + 20 shipiron']]);
async function loadNavyGuide(topic){try{const r=await fetch('records/'+topic+'.txt');if(!r.ok)throw Error('Unavailable');const text=await r.text();document.querySelector('[data-guide-source="'+topic+'"]').textContent=text;if(topic==='mapold'){const map=document.createElement('pre');map.className='map-reference';map.textContent=text.slice(text.indexOf('++===='));document.querySelector('#guide-visual-mapold').append(map);}if(topic==='shipequipment'){const chunks=text.split(/^==(.+?)==\s*$/gm);document.querySelector('#guide-details-shipequipment').innerHTML='<p class="label">EQUIPMENT ENTRIES · REFORMATTED SOURCE WORDING</p><div class="equipment-grid">'+chunks.slice(1).reduce((cards,part,i,parts)=>i%2===0?cards+'<article><h3>'+activitySafe(part.trim())+'</h3><p>'+activitySafe((parts[i+1]||'').trim()).replaceAll('\n','<br>')+'</p></article>':cards,'')+'</div>';}if(topic==='statues'){const locations=text.slice(text.indexOf(' BAY OF DARDANOS'),text.indexOf(' STATUE OF NERAEOS FYLAKAS'));const el=document.createElement('pre');el.className='map-reference';el.textContent=locations;document.querySelector('#guide-visual-statues').append(el);}}catch{document.querySelector('[data-guide-source="'+topic+'"]').textContent='Use the exact source link above.';}}
Object.keys(navyGuides).forEach(loadNavyGuide);
document.querySelector('#ships-book summary .small').textContent='Ship directory, readiness, and all seven preparation guides supplied';
document.querySelector('#chartroom summary .small').textContent='Harbours, directions, old map, and statues supplied · MAPNEW outstanding';
