/* Read published Merchant records as data; never execute their scripts. */
(() => {
  const root='https://raw.githubusercontent.com/oddtotheendart-source/grand-mercs-calendar/main/';
  const publicRoot='https://oddtotheendart-source.github.io/grand-mercs-calendar/';
  const months=['Sarapin','Daedalan','Aeguary','Miraman','Scarlatan','Ero','Valnuary','Lupar','Phaestian','Chronos','Glacian','Mayan'];
  const serial=([y,m,d])=>y*300+months.indexOf(m)*25+d-1;
  const panel=document.createElement('section');panel.className='merchant-events';
  panel.innerHTML='<h3>Shared Merchants events</h3><p>Published Merchant and festival records, shared here for Navy readers.</p><p id="merchant-sync" role="status">Loading published events…</p><div id="merchant-event-list"></div><details><summary>Festival host periods and planned activities</summary><div id="merchant-period-list"></div></details><p><a href="'+publicRoot+'calendar.html">Open the Merchants calendar</a> · <a href="'+publicRoot+'crucible.html">Open Prospero’s Crucible planner</a></p>';
  document.querySelector('#game-day-details').after(panel);
  let schedule={events:[],periods:[]};
  function text(tag,value){const el=document.createElement(tag);el.textContent=value;return el;}
  function apply(data,status){schedule=data;window.merchantSchedule=data;const list=panel.querySelector('#merchant-event-list');list.replaceChildren();
    data.events.slice().sort((a,b)=>serial([a.year,a.month,a.day])-serial([b.year,b.month,b.day])).forEach(e=>{const b=document.createElement('button');b.type='button';b.append(text('strong',e.title),text('span',`${e.host} · ${e.day} ${e.month}, ${e.year} AF`));if(e.realTime)b.append(text('small',e.realTime));b.addEventListener('click',()=>{const year=document.querySelector('#game-year');year.value=e.year;year.dispatchEvent(new Event('input'));const day=document.querySelector(`.navy-days button[aria-label="${e.day} ${e.month}, ${e.year} AF"]`);day.click();day.scrollIntoView({block:'center',behavior:'smooth'});});list.append(b);});
    const periods=panel.querySelector('#merchant-period-list');periods.replaceChildren();data.periods.forEach(p=>{const article=document.createElement('article');article.append(text('h4',p.host),text('p',`${p.start[2]} ${p.start[1]}, ${p.start[0]} AF – ${p.end[2]} ${p.end[1]}, ${p.end[0]} AF`));if(p.items?.length){const ul=document.createElement('ul');p.items.forEach(i=>ul.append(text('li',i)));article.append(ul);}periods.append(article);});
    panel.querySelector('#merchant-sync').textContent=status;window.dispatchEvent(new Event('merchant-schedule-loaded'));
  }
  window.addEventListener('merchant-calendar-day',event=>{const {year,month,day}=event.detail;const out=document.querySelector('#game-day-details');out.replaceChildren(text('strong',`${day} ${month}, ${year} AF`));const events=schedule.events.filter(e=>e.year===year&&e.month===month&&e.day===day);const n=serial([year,month,day]);const periods=schedule.periods.filter(p=>n>=serial(p.start)&&n<=serial(p.end));events.forEach(e=>out.append(text('p',e.host+' — '+e.title+(e.realTime?' · '+e.realTime:' · Real-world time awaiting confirmation.'))));periods.forEach(p=>out.append(text('p','Festival host period: '+p.host)));if(!events.length)out.append(text('p','No dated event recorded for this day.'));});
  async function load(){let fallback;try{fallback=await (await fetch('records/merchant-calendar-snapshot.json')).json();apply(fallback,'Saved Merchants snapshot: 1 October 2026. Checking for updates…');}catch{}
    try{const response=await fetch(root+'app.js',{signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error();const app=await response.text();const events=[...app.matchAll(/^\s*\[(\d+),"([^"]+)",(\d+),"([^"]+)","([^"]+)"\]/gm)].map(m=>({year:+m[1],month:m[2],day:+m[3],host:m[4],title:m[5]}));const periods=[...app.matchAll(/\{start:\[(.*?)\],end:\[(.*?)\],host:"([^"]+)"(?:,items:(\[[^\n]*?\]))?\}/g)].map(m=>({start:JSON.parse('['+m[1]+']'),end:JSON.parse('['+m[2]+']'),host:m[3],items:m[4]?JSON.parse(m[4]):[]}));if(!events.length||!periods.length)throw Error();
      let crucibleStatus='Crucible record: saved 1 October 2026 copy.';
      try{const res=await fetch(root+'crucible.html',{signal:AbortSignal.timeout(10000)});if(!res.ok)throw Error();const doc=new DOMParser().parseFromString(await res.text(),'text/html');const current=doc.querySelector('.crucible-current .trade-detail');const date=/(\d+)(?:st|nd|rd|th)? of (\w+), (\d+) AF/.exec(current?.textContent||'');if(!date||!months.includes(date[2]))throw Error();const real=/\(\(OOC: (.*?)\)\)/.exec(current.textContent);events.push({year:+date[3],month:date[2],day:+date[1],host:'Grand Merchant Collective',title:'Prospero’s Crucible — '+current.querySelector('h3').textContent,source:'crucible',realTime:real?real[1]+' — check the source for its time zone.':undefined});crucibleStatus='Crucible date checked on this visit.';}catch{events.push(...(fallback?.events||[]).filter(e=>e.source==='crucible'));}
      apply({events,periods},'Festival dates checked against the Merchants site on this visit. '+crucibleStatus);
    }catch{panel.querySelector('#merchant-sync').textContent=fallback?'Showing saved Merchants records from 1 October 2026; live update unavailable. Use the source links for the latest changes.':'Merchants records unavailable. Use the source links below.';}
  }
  load();
})();
