(() => {
  const returns=[
    ['help-ships','ships-book','Ships: the public overview','HELP 23.1','Harbour → board → inspect','Use HARBOUR SHIPS to see docked vessels and BOARD SHIP <ship name|ship #> to board. Man-made harbours offer more services than natural harbours. The return describes commissioning at a shipyard and sailing aboard another adventurer’s vessel.'],
    ['help-new-to-ships','ships-book','Getting a ship ready','HELP 23.2','Crew → provisions → strongbox → return → equipment','Inspect SHIP INFO [BRIEF], SHIP CREW, SHIP STORES CHECK, and SHIP STRONGBOX CHECK. Hire crew and shipmates; stock provisions, tokens, and docking gold; set SHIPRETURN HERE and perform the seaprayer ritual. This is general public guidance. The separate Navy fleet scroll governs city-ship stores and return requirements.'],
    ['help-sailing','chartroom','Sailing with the wind','HELP 23.3','Choose a course relative to the wind','No ship can sail directly into the wind. The table gives relative movement values, not knots or travel times. In the source’s example, a north wind comes from the north and moves south. Larboard is left when facing forward; starboard is right. The source includes the points-of-sail diagram and sailing vocabulary.'],
    ['help-ship-races','voyage-board','Joining a ship race','HELP 23.4','Join → bearings → enter start → legs → finish','A captain or owner aboard uses SHIPRACE JOIN. SHIPRACE BEARINGS gives the direction of the next marker; CONFIG SHIPRACE ON enables notices. Enter a starting-line location after the race starts—waiting on it does not begin the race. Pass through each leg marker, then the finish. The return lists 13 courses. No active race is implied.'],
    ['help-ship-command','watch-bill','Spoken ship orders','HELP 23.5','SAY the order to your executive officer','These are verbal orders relayed by the executive officer to denizen crew. SAY the orders rather than assuming every phrase is a direct SHIP command. The supplied table covers movement, course, docking, anchors, planks, flags, grappling, and ladders. This public HELP is separate from the Navy’s CLHELP COMMAND specialisation record.'],
    ['help-ship-repair','ships-book','Repairing hull, sails, and weapons','HELP 23.6','Shipmates → repair order → status','Sails and hull wear with use and time; decay is reduced in a harbour. At least one shipmate is required to commence denizen repairs. More shipmates improve speed up to the listed maximum. Deckhands also have MAINT options. SHIP WEAPONREPAIR <weapon> requires 1 wood, 1 rope, and 1 iron per repair.'],
    ['help-high-seas','chartroom','Sea conditions and rowing','HELP 23.7','Glassy I → raging IX','The source lists nine sea states. Rowing slows at IV (choppy) or greater; in VIII (tempestuous) and IX (raging), it is almost useless. These states describe water conditions, not a calculated route duration.']
  ];
  for(const [id,section,title,command,quick,prose] of returns){const body=document.querySelector('#'+section+' .reference-body');const detail=document.createElement('details');detail.className='reference guide-detail';detail.id=id;detail.innerHTML='<summary><div><span class="label">'+command+' · PUBLIC GAME HELP</span><h2>'+title+'</h2></div><span class="toggle" aria-hidden="true">+</span></summary><div class="reference-body"><div class="at-glance"><p class="label">01 / AT A GLANCE</p><h3>'+quick+'</h3><div class="public-help-visual"></div></div><div class="editorial"><p class="label">02 / WORKING REFERENCE · EDITORIAL</p><p>'+activitySafe(prose)+'</p><p>Returned in game on 2 October 2026. Public HELP and Hashani clan policy remain separate sources.</p></div><details class="source-box"><summary>03 / ORIGINAL '+command+' RETURN</summary><p><a href="records/'+id+'.txt">Read the extracted help return</a></p><pre class="exact-scroll activity-source">Loading the supplied source…</pre></details></div>';body.append(detail);fetch('records/'+id+'.txt').then(r=>{if(!r.ok)throw Error();return r.text();}).then(text=>detail.querySelector('pre').textContent=text).catch(()=>detail.querySelector('pre').textContent='Use the source link above.');
    const visual=detail.querySelector('.public-help-visual');
    if(id==='help-sailing')visual.innerHTML=basicsTable('Relative movement values from HELP SAILING',['Points off wind','War Galley','Seastrider','Windcutter'],[[0,0,0,0],[1,0,0,2],[2,2,3,4],[3,4,4,5],[4,6,6,7],[5,8,8,8],[6,10,9,8],[7,11,10,9],[8,12,10,9]].map(r=>r.map(String)));
    if(id==='help-ship-repair')visual.innerHTML=basicsTable('Shipmates for repairs: recommendation and useful maximum',['Vessel','Recommended','Useful maximum'],[['Windcutter','3','15'],['Seastrider','8','40'],['War Galley','15','50']])+'<p>Commands: <code>SHIP REPAIR ALL</code>, <code>SHIP REPAIR STATUS</code>, <code>SHIP REPAIR NONE|STOP</code>. These repair recommendations differ from the Navy crew guide’s larger recommended complements; both records remain visible.</p>';
    if(id==='help-ship-command')visual.innerHTML='<p><code>SAY ALL STOP</code> · <code>SAY COURSE &lt;direction&gt;</code> · <code>SAY DOCK &lt;direction&gt;</code></p><p>See the source table for accepted alternatives and optional words.</p>';
  }
  const catalogue=document.createElement('details');catalogue.className='source-box';catalogue.innerHTML='<summary>Public ship HELP received from the 2 October logs</summary><p>Seven public returns, separate from the clan-scroll catalogue.</p><div class="chips">'+returns.map(([id,,title,command])=>'<a href="#'+id+'">'+command+' · '+title+'</a>').join('')+'</div>';document.querySelector('#all-scrolls').append(catalogue);
  if(returns.some(([id])=>location.hash==='#'+id))openDestination();
})();
