'use strict';
const hero=document.querySelector('.hero');
const motionButton=document.createElement('button');
motionButton.type='button';motionButton.className='motion-control';
motionButton.textContent='Pause header motion';motionButton.setAttribute('aria-pressed','false');
motionButton.addEventListener('click',()=>{const paused=hero.classList.toggle('motion-paused');motionButton.setAttribute('aria-pressed',String(paused));motionButton.textContent=paused?'Resume header motion':'Pause header motion';});
hero.append(motionButton);
const sections = [
 ['quarterdeck','The Quarterdeck','I have just joined','welcome whatnow basiccommands progression seafaring',['Welcome','First steps','Commands','Progression'],'For a first reading, begin with the welcome and introductory scrolls, then consult the command and progression records. This order is a reading guide; the Navy’s requirements must be taken from the original text.'],
 ['watch-bill','The Watch Bill','I need to choose a shipboard role','specialisations specialists command deckhand helm watch weapons',['Command','Deckhand','Helm','Watch','Weapons'],'Consult the specialisation records before turning to the scroll for a particular station. Duties, qualifications, and assignments remain to be transcribed from the Navy record.'],
 ['ships-book',"The Ship’s Book",'I need to prepare a ship','ships shiptypes cityships crew newship buyingaship shipequipment shipfitting seaspells needammo',['Vessel','Crew','Equipment','Fitting','Ammunition'],'Here shall be gathered the vessel records and preparations for sea. Class requirements, provisions, strongbox amounts, and return arrangements await the exact cityships scroll; no operational figures are supplied in this edition.'],
 ['chartroom','The Chartroom','I need to find a route','mapnew mapold harbours harbourdirections statues',['Maps','Harbours','Directions','Statues'],'Read the harbour and direction records alongside the available maps. This section contains a topic guide only; no charted position or sailing route has yet been verified.'],
 ['battle-stations','Battle Stations','We are under attack, or need combat guidance','ammo combattraining combatvolunteers nwtintro nwtcrew nwtstrategy sailors targetlist underattack sunk',['Under attack','Ammunition','Crew','Strategy','Sunk'],'The combat and incident scrolls belong together for ready consultation. Procedures will be entered from the original records. The targetlist helpfile is missing; this page supplies no target names or engagement instructions.'],
 ['hunting-chart','The Hunting Chart','I want to hunt or dive','seamonsters seamonsterareas kraken deepseadiving deepseatreasure',['Creatures','Areas','Kraken','Diving','Treasure'],'The creature, area, and diving records shall form the hunting reference. Locations, hazards, and methods require source text before they may be stated here.'],
 ['merchants-ledger',"The Merchant’s Ledger",'I want to trade cargo','shiptrades tradecargo tradedealchart trademath traderewards traderouteguide',['Cargo','Deals','Calculations','Rewards','Routes'],'Consult cargo and deal records before the calculation and route guides. Prices, rewards, and routes are reserved for verified source material; this edition makes no trading recommendation.'],
 ['voyage-board','The Voyage Board','I want to plan a voyage','voyages voyagelist bounties',['Voyage records','Voyage list','Bounties'],'The voyage and bounty records shall be gathered here. Available undertakings and their conditions await transcription; no active voyage or bounty is implied.']
].map(([id,title,question,topics,flow,prose])=>({id,title,question,topics:topics.split(' '),flow,prose}));
document.getElementById('task-grid').innerHTML=sections.map((s,i)=>`<a class="task-card" href="#${s.id}"><span class="number">${String(i+1).padStart(2,'0')}</span><h3>${s.title}</h3><p>${s.question}</p><span class="arrow" aria-hidden="true">↗</span></a>`).join('');
document.getElementById('references').innerHTML=sections.map(s=>`<details class="reference" id="${s.id}"><summary><div><span class="label">${s.question}</span><h2>${s.title}</h2><span class="small">Reading guide · original text awaiting transcription</span></div><span class="toggle" aria-hidden="true">+</span></summary><div class="reference-body"><div class="at-glance"><p class="label">01 / AT A GLANCE · TOPIC GUIDE</p><div class="topic-flow">${s.flow.map(t=>`<span>${t}</span>`).join('<b aria-hidden="true">›</b>')}</div></div><div class="editorial"><p class="label">02 / THE WORKING REFERENCE · EDITORIAL</p><p>${s.prose}</p></div><details class="source-box"><summary>03 / THE ORIGINAL SCROLLS</summary><p>These topics are catalogued from the site plan. Exact helpfile bodies and author attributions are not present in the available files. Open a topic below for its source status.</p><div class="chips">${s.topics.map(t=>`<a href="#scroll-${t}">CLHELP ${t.toUpperCase()}</a>`).join('')}</div></details></div></details>`).join('');
const records=sections.flatMap(s=>s.topics.map(topic=>({topic,section:s.title})));
document.getElementById('scroll-list').innerHTML=records.map(r=>`<details class="scroll-record" id="scroll-${r.topic}" data-search="${r.topic} ${r.section.toLowerCase()}"><summary><code>CLHELP ${r.topic.toUpperCase()}</code><span class="small">${r.section} · ${r.topic==='targetlist'?'Missing helpfile':'Awaiting original text'}</span></summary><p>${r.topic==='targetlist'?'The targetlist helpfile is explicitly missing. No replacement text or target list has been invented.':'Exact source text and the composed-by attribution have not yet been supplied. This space is reserved for a verbatim transcription of a successfully returned helpfile.'}</p></details>`).join('');
const search=document.getElementById('scroll-search');
function filter(){let count=0;document.querySelectorAll('.scroll-record').forEach(el=>{el.hidden=!el.dataset.search.includes(search.value.trim().toLowerCase());if(!el.hidden)count++;});document.getElementById('result-count').textContent=`${count} of ${records.length} scroll topics${count===0?' — no matching topics':''}`;}
search.addEventListener('input',filter);filter();
function openDestination(){const id=decodeURIComponent(location.hash.slice(1));const el=document.getElementById(id);if(!el)return;if(el.classList.contains('scroll-record')){search.value='';filter();}if(el.tagName==='DETAILS')el.open=true;for(let parent=el.parentElement;parent;parent=parent.parentElement){if(parent.tagName==='DETAILS')parent.open=true;}requestAnimationFrame(()=>el.scrollIntoView({block:'start'}));}
window.addEventListener('hashchange',openDestination);if(location.hash)openDestination();
