(() => {
  const planner=document.createElement('section');planner.id='selected-trade-planner';planner.className='at-glance';
  planner.innerHTML=`<p class="label">SELECT A DEAL · PLAN THE CARGO</p><h3>Ship trade planner</h3><p>Choose a recorded deal, then choose how to obtain its cargo. Check <code>HARBOUR INFO</code> for the actual offer and restrictions before sailing.</p>
    <div class="calc-grid"><label>Recorded trade deal<select id="planner-deal"></select></label><label>Number of deliveries<input id="planner-count" type="number" min="1" max="100" step="1" value="1"></label><label>Ship type<select id="planner-ship"><option value="75">Cutter</option><option value="100" selected>Seastrider</option><option value="150">Galley</option><option value="custom">Custom</option></select></label>
    <label>Usable cargo capacity<input id="planner-capacity" type="number" min="0" step="1" value="100"></label><label>Accept trade at<select id="planner-start"><option>Tasur'ke</option><option>Thraasi</option></select></label><label>Deliver trade at<select id="planner-end"><option>Tasur'ke</option><option>Thraasi</option></select></label></div>
    <p class="small">Ship capacities are workbook defaults; replace with your actual usable capacity. The two trade harbours are planning choices, not a claim that this deal is offered at both.</p>
    <label for="planner-existing">Cargo already aboard — one line per cargo, such as <code>Granite: 3</code></label><textarea id="planner-existing" rows="3" placeholder="Granite: 3&#10;Marble: 2"></textarea>
    <label>Other occupied cargo space<input id="planner-occupied" type="number" min="0" step="1" value="0"></label><p class="small">Cargo listed above is counted automatically. Use this field only for other cargo not listed.</p>
    <div id="planner-options"></div><div id="planner-output" aria-live="polite">Loading recorded deals…</div>
    <details class="source-box"><summary>Sources and calculation notes</summary><p><a href="records/trade-planner-data.json">Extracted workbook records</a> · <a href="records/tradecargo.txt">TRADECARGO</a> · <a href="records/traderouteguide.txt">TRADEROUTEGUIDE</a> · <a href="records/shiptrades.txt">SHIPTRADES</a></p><p>The plan buys and exchanges whole ratio batches, keeps leftovers aboard, and counts a docking fee whenever the harbour changes. The initial acceptance docking fee is excluded because the plan starts aboard a docked ship. Suliel defaults to the recorded west-harbour fee of 500; edit it to 0 for the east harbour. Ageiro uses TRADECARGO’s recorded no-fee value instead of the workbook’s Unknown. No sailing time or geographic shortest route is inferred.</p><p>Multiple deliveries only scale cargo and rewards. Additional acceptance/delivery trips, eligibility, crew costs, supplies, and other charges are outside this estimate. Workbook Cleanup is excluded because it is not a recorded reward offer.</p></details>`;
  document.querySelector('#activity-extra-trademath').prepend(planner);
  const safe=activitySafe;
  let data;const choices={};const fees={};
  function integer(id){const n=Number(planner.querySelector('#'+id).value);if(!planner.querySelector('#'+id).value.trim()||!Number.isSafeInteger(n)||n<0)throw Error('Enter whole, non-negative quantities and capacity.');return n;}
  function inventory(){const result={};const names=[...new Set(data.exchanges.flatMap(e=>[e.input,e.output]).filter(n=>n!=='Sovereigns'))];for(const line of planner.querySelector('#planner-existing').value.split('\n').filter(l=>l.trim())){const match=/^\s*([^:]+):\s*(\d+)\s*$/.exec(line);if(!match)throw Error('Use Cargo: quantity for each cargo line.');const name=names.find(n=>n.toLowerCase()===match[1].trim().toLowerCase());if(!name)throw Error('Unrecognised cargo: '+match[1]+'. Use the workbook cargo names (for example Kawhe, Fruit, Furs).');const quantity=Number(match[2]);if(!Number.isSafeInteger(quantity))throw Error('Cargo quantity is too large.');result[name]=(result[name]||0)+quantity;}return result;}
  function exchange(cargo){const options=data.exchanges.filter(e=>e.output===cargo);if(!options.length)throw Error('No recorded exchange for '+cargo+'.');return options.find(e=>e.input===choices[cargo])||options.find(e=>e.input===data.preferred[cargo])||options[0];}
  function calculate(){const output=planner.querySelector('#planner-output');const options=planner.querySelector('#planner-options');if(!data)return;
    try{const deal=data.deals.find(d=>String(d.id)===planner.querySelector('#planner-deal').value);const count=integer('planner-count');if(count<1||count>100)throw Error('Choose 1–100 deliveries.');const capacity=integer('planner-capacity');const occupied=integer('planner-occupied');const initial=inventory();const pool={...initial};const target=deal.quantity*count;const steps=[];const active=[];
      function need(cargo,amount,path=[]){const available=Math.min(pool[cargo]||0,amount);pool[cargo]=(pool[cargo]||0)-available;const remaining=amount-available;if(!remaining)return;if(path.includes(cargo))throw Error('These exchange choices form a loop through '+cargo+'. Choose a different source.');const e=exchange(cargo);active.push(cargo);const batches=Math.ceil(remaining/e.out);const cost=batches*e.cost;const gained=batches*e.out;if(!Number.isSafeInteger(cost)||!Number.isSafeInteger(gained))throw Error('The quantity is too large.');if(e.input!=='Sovereigns')need(e.input,cost,[...path,cargo]);steps.push({...e,cost,gained});}
      need(deal.cargo,target);
      const controls=[...new Set(active)].map(cargo=>{const opts=data.exchanges.filter(e=>e.output===cargo);const selected=exchange(cargo);return '<label>'+safe(cargo)+' from<select data-cargo="'+safe(cargo)+'">'+opts.map(e=>'<option value="'+safe(e.input)+'"'+(e===selected?' selected':'')+'>'+safe(e.input)+' → '+safe(e.harbour)+' ('+e.cost+':'+e.out+')</option>').join('')+'</select></label>';}).join('');
      options.innerHTML='<h3>Exchange choices for this plan</h3><div class="calc-grid">'+controls+'</div>';
      options.querySelectorAll('select').forEach(s=>s.addEventListener('change',()=>{choices[s.dataset.cargo]=s.value;calculate();}));
      const holdings={...initial};let peak=occupied+Object.values(holdings).reduce((a,b)=>a+b,0);let previous=planner.querySelector('#planner-start').value;let gold=0,docking=0;const rows=[];
      function dock(harbour,fee){const changed=harbour!==previous;previous=harbour;return changed?fee:0;}
      for(const [index,step] of steps.entries()){if(step.input==='Sovereigns')gold+=step.cost;else{holdings[step.input]=(holdings[step.input]||0)-step.cost;if(holdings[step.input]<0)throw Error('Insufficient planned input cargo.');}holdings[step.output]=(holdings[step.output]||0)+step.gained;const onboard=occupied+Object.values(holdings).reduce((a,b)=>a+b,0);peak=Math.max(peak,onboard);const fee=fees[step.harbour]??step.fee;const charged=dock(step.harbour,fee);docking+=charged;rows.push('<tr><td>'+(index+1)+'</td><td>'+safe(step.harbour)+'</td><td>'+step.cost+' '+safe(step.input)+'</td><td>'+step.gained+' '+safe(step.output)+'</td><td><input type="number" min="0" step="1" aria-label="Docking fee for '+safe(step.harbour)+'" data-fee="'+safe(step.harbour)+'" value="'+fee+'"><small>Charged: '+charged+'</small></td><td>'+onboard+(onboard>capacity?' · OVER CAPACITY':'')+'</td></tr>');}
      const end=planner.querySelector('#planner-end').value;const deliveryFee=dock(end,2000);docking+=deliveryFee;holdings[deal.cargo]=(holdings[deal.cargo]||0)-target;
      const leftovers=Object.entries(holdings).filter(([,n])=>n>0).map(([cargo,n])=>n+' '+cargo).join(', ')||'None';const total=gold+docking;const cashReward=deal.gold>0?deal.gold*count:null;
      output.innerHTML='<h3>'+target+' '+safe(deal.cargo)+' for '+safe(deal.reward)+'</h3><p><strong>Cargo purchases:</strong> '+gold.toLocaleString()+' gold · <strong>Docking:</strong> '+docking.toLocaleString()+' gold · <strong>Recorded route cost:</strong> '+total.toLocaleString()+' gold</p><p>'+(cashReward!==null?'Gold reward: '+cashReward.toLocaleString()+' · Reward less recorded route cost: '+(cashReward-total).toLocaleString()+' gold.':'Non-gold reward; no gold value assigned.')+'</p><p><strong>Peak cargo:</strong> '+peak+' / '+capacity+(peak>capacity?' — OVER CAPACITY. Reduce the quantity or use more space.':'')+'</p>'+(count>1?'<p>Check personal/ship restrictions. Additional trips for repeat acceptances or deliveries are not costed.</p>':'')+'<div class="table-scroll"><table><thead><tr><th>Step</th><th>Harbour</th><th>Give / buy with</th><th>Receive</th><th>Docking fee</th><th>Onboard</th></tr></thead><tbody>'+rows.join('')+'<tr><td>Deliver</td><td>'+safe(end)+'</td><td>'+target+' '+safe(deal.cargo)+'</td><td>'+safe(deal.reward)+'</td><td>'+deliveryFee+'</td><td>'+Math.max(0,occupied+Object.values(holdings).reduce((a,b)=>a+b,0))+'</td></tr></tbody></table></div><p><strong>Cargo remaining:</strong> '+safe(leftovers)+'</p>';
      output.querySelectorAll('[data-fee]').forEach(input=>input.addEventListener('change',()=>{const n=Number(input.value);if(!input.value.trim()||!Number.isSafeInteger(n)||n<0){input.setCustomValidity('Enter a whole non-negative fee.');input.reportValidity();return;}fees[input.dataset.fee]=n;calculate();}));
    }catch(error){output.textContent=error.message;}
  }
  planner.querySelector('#planner-ship').addEventListener('change',event=>{if(event.target.value!=='custom')planner.querySelector('#planner-capacity').value=event.target.value;calculate();});
  planner.querySelector('#planner-capacity').addEventListener('input',()=>planner.querySelector('#planner-ship').value='custom');
  planner.querySelectorAll('input,textarea,select').forEach(el=>el.addEventListener(el.tagName==='SELECT'?'change':'input',calculate));
  fetch('records/trade-planner-data.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(records=>{data=records;planner.querySelector('#planner-deal').innerHTML=data.deals.map(d=>'<option value="'+d.id+'"'+(d.id===45?' selected':'')+'>'+d.id+' · '+safe(d.reward)+' for '+d.quantity+' '+safe(d.cargo)+'</option>').join('');calculate();}).catch(()=>planner.querySelector('#planner-output').textContent='Unable to load the recorded trade data. Refresh to try again.');
})();
